### ISSUE TITLE
networkit.generators

### ISSUE THREAD

**Issue by varsha2611** [kit-parco/networkit#113]
I am trying to run the function `networkit.generators.BTERReplicator()` but i am facing the following issue
```
error: 'tricnt_mex' undefined near line 83 column 9
error: called from
    tricnt at line 83 column 7
    ccperdeg at line 97 column 12
    /tmp/tmpz9d47pum/bter_wrapper.m at line 7 column 11
Traceback (most recent call last):
  File "test_other_generators.py", line 93, in <module>
    mesh_G_replica = BTER_generator(mesh_G)
  File "test_other_generators.py", line 16, in BTER_generator
    G_replica = gen.generate()
  File "/home/varsha/.local/lib/python3.5/site-packages/networkit/generators.py", line 65, in generate
    G_bter = graphio.readMat(tempFileOut, key='G_bter')
  File "/home/varsha/.local/lib/python3.5/site-packages/networkit/graphio.py", line 181, in readMat
    matlabObject = scipy.io.loadmat(path)
  File "/home/varsha/.local/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 141, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/home/varsha/.local/lib/python3.5/site-packages/scipy/io/matlab/mio.py", line 64, in mat_reader_factory
    byte_stream, file_opened = _open_file(file_name, appendmat)
TypeError: 'NoneType' object is not iterable

```
I am also trying to use `networkit.generators.RmatGenerator' i am not sure what path is required in setPath

```
Traceback (most recent call last):
  File "test_other_generators.py", line 95, in <module>
    mesh_G_replica = RMAT_generator(mesh_G)
  File "test_other_generators.py", line 28, in RMAT_generator
    gen.fit(G, scale=1)
  File "networkit/_NetworKit.pyx", line 2520, in networkit._NetworKit.RmatGenerator.fit (networkit/_NetworKit.cpp:29158)
  File "networkit/_NetworKit.pyx", line 2522, in networkit._NetworKit.RmatGenerator.fit (networkit/_NetworKit.cpp:28233)
RuntimeError: call setPaths class method first to configure

```

Could you please help me with same.
Thanks in advance

**Comment by hmeyerhenke** [comment]
The BTER generator probably needs the external Matlab files of BTER. I haven't worked with it myself, so that I cannot tell you more details. Maybe @michitux  can?

RMAT should be no problem, though. Did you import NetworKit correctly? 

Look here [1] at the end of the page for an example for the hyperbolic random graph generator. For RMAT the call is quite similar (different parameters, though).

[1] https://networkit.iti.kit.edu/get_started.html

**Comment by avdgrinten** [comment]
Closing as no further info was provided.

**Comment by bokveizen** [comment]
For anyone who might encounter this issue later, you may need the files at https://github.com/kd383/NetworkDOS/tree/e9bfe79163a669b3d6f80b3287ca6196ce4860e0/Matlab/code/model/bter

**Comment by bokveizen** [comment]
Also I found the new version of feastpack here https://www.mathsci.ai/feastpack/
